version: "3"
services:
  mysqldb:
    image: biospa-mysql
    container_name: biospa-mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_NAME=${DB_NAME}
        - DB_PORT=${DB_PORT}
        - SERVER_PORT=${SERVER_PORT}
        - CLIENT_ORIGIN=$CLIENT_ORIGIN
        - SMTP_TO_EMAIL=$SMTP_TO_EMAIL
        - SMTP_TO_PASSWORD=$SMTP_TO_PASSWORD
    restart: always
    env_file: ./.env
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

    depends_on:
      - mysqldb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    #request will forward to same url, so we only need /api to distinguish that this request will forward to our backend
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - REACT_APP_API_URL=$CLIENT_API_BASE_URL
  #  ports:
  #    - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 3000:80
    restart: always

volumes:
  db-volume:
